STYLE_RECIPES = {
    "active-theory": {
        "name": "Active Theory (Cinematic WebGL)",
        "school": "Motion / Experimental",
        "palette": {"primary": "#1a1a1a", "accent": "#667eea", "bg": "#ffffff", "text": "#1a1a1a", "muted": "#888", "border": "#e5e7eb"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "aesop": {
        "name": "Aesop Skincare",
        "school": "Editorial / Minimalist",
        "palette": {"primary": "#E8E4D9", "accent": "#F0EDE4", "bg": "#F2EFE5", "text": "#E8E4D9", "muted": "#1B1B1B", "border": "#7A8470"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "apple-hig": {
        "name": "Apple Human Interface",
        "school": "Editorial / Minimalist",
        "palette": {"primary": "#FFFFFF", "accent": "#D2D2D7", "bg": "#000000", "text": "#FFFFFF", "muted": "#1D1D1F", "border": "#F5F5F7"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "are-na": {
        "name": "Are.na (Honest Web)",
        "school": "Brutalist / Raw",
        "palette": {"primary": "#FFFFFF", "accent": "#F4F1E8", "bg": "#000000", "text": "#FFFFFF", "muted": "#0000EE", "border": "#551A8B"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "balenciaga-post-2017": {
        "name": "Balenciaga (post-Demna era)",
        "school": "Brutalist / Raw",
        "palette": {"primary": "#000000", "accent": "#F5F4F0", "bg": "#FFFFFF", "text": "#000000", "muted": "#F5F4F0", "border": "#e5e7eb"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "bloomberg-businessweek-turley": {
        "name": "Bloomberg Businessweek (Turley Era)",
        "school": "Brutalist / Raw",
        "palette": {"primary": "#FF3D00", "accent": "#000000", "bg": "#FFE800", "text": "#FF3D00", "muted": "#001AFF", "border": "#FFFFFF"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "bloomberg-terminal": {
        "name": "Bloomberg Terminal",
        "school": "Information Architecture",
        "palette": {"primary": "#0A0E1A", "accent": "#2A3050", "bg": "#11172A", "text": "#0A0E1A", "muted": "#1A2138", "border": "#FFA02F"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "dieter-rams-braun": {
        "name": "Dieter Rams / Braun",
        "school": "Editorial / Minimalist",
        "palette": {"primary": "#E4E1DC", "accent": "#F5C518", "bg": "#F5F4F0", "text": "#E4E1DC", "muted": "#191919", "border": "#A8A8A8"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "field-io": {
        "name": "Field.io (Generative Motion Identity)",
        "school": "Motion / Experimental",
        "palette": {"primary": "#0B0B0F", "accent": "#A0A4B0", "bg": "#000000", "text": "#0B0B0F", "muted": "#0CE0E5", "border": "#5B2EFF"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "headspace-meditation": {
        "name": "Headspace / Calm",
        "school": "Warm Humanist",
        "palette": {"primary": "#FFE2C5", "accent": "#F5867B", "bg": "#FFEDD5", "text": "#FFE2C5", "muted": "#F4A573", "border": "#1B3A47"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "linear": {
        "name": "Linear (Modern Builder Tool)",
        "school": "Modern Tool / Builder SaaS",
        "palette": {"primary": "#08090A", "accent": "#A78BFA", "bg": "#16171C", "text": "#08090A", "muted": "#1E1F25", "border": "#26272E"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "mailchimp-freddie": {
        "name": "Mailchimp (Freddie Era, c. 2018–2022)",
        "school": "Warm Humanist",
        "palette": {"primary": "#FFE01B", "accent": "#FF4D74", "bg": "#FFFFFF", "text": "#FFE01B", "muted": "#241C15", "border": "#FBEFE3"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "mid-century-modern": {
        "name": "Mid-Century Modern (Paul Rand / Saul Bass)",
        "school": "Specialty / Genre (also touches Information Architecture)",
        "palette": {"primary": "#EBE3D2", "accent": "#1A1A18", "bg": "#D9A441", "text": "#EBE3D2", "muted": "#3D6E70", "border": "#1A1A18"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "monocle-magazine": {
        "name": "Monocle Magazine",
        "school": "Editorial / Minimalist",
        "palette": {"primary": "#F2EFE7", "accent": "#C8C2B0", "bg": "#1A1A1A", "text": "#F2EFE7", "muted": "#C7322E", "border": "#5E6347"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "muji-kenya-hara": {
        "name": "MUJI / Kenya Hara",
        "school": "Editorial / Minimalist",
        "palette": {"primary": "#F4F2EC", "accent": "#C8161D", "bg": "#FFFFFF", "text": "#F4F2EC", "muted": "#2A2A28", "border": "#000000"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "notion-pre-ai": {
        "name": "Notion (pre-AI era, c. 2017–2022)",
        "school": "Modern Tool / Builder SaaS (warm-leaning, near Humanist border)",
        "palette": {"primary": "#FFFFFF", "accent": "#FEF3C7", "bg": "#F7F6F3", "text": "#FFFFFF", "muted": "#37352F", "border": "#787774"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "8px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "nyt-the-daily": {
        "name": "New York Times Editorial",
        "school": "Information Architecture",
        "palette": {"primary": "#FFFFFF", "accent": "#E2E2E2", "bg": "#121212", "text": "#FFFFFF", "muted": "#666666", "border": "#D0021B"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "pentagram": {
        "name": "Pentagram / Paula Scher",
        "school": "Information Architecture",
        "palette": {"primary": "#000000", "accent": "#EFE9DC", "bg": "#FFFFFF", "text": "#000000", "muted": "#1E3FFF", "border": "#F4F1E7"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "raycast": {
        "name": "Raycast (Productivity Tool)",
        "school": "Modern Tool / Builder SaaS",
        "palette": {"primary": "#0F0F11", "accent": "#FF6363", "bg": "#FFFFFF", "text": "#0F0F11", "muted": "#B0B3B8", "border": "#FF6363"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "resn-storytelling": {
        "name": "Resn (Story Through Scroll)",
        "school": "Motion / Experimental",
        "palette": {"primary": "#1a1a1a", "accent": "#667eea", "bg": "#ffffff", "text": "#1a1a1a", "muted": "#888", "border": "#e5e7eb"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "6px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "stripe-press": {
        "name": "Stripe Press",
        "school": "Warm Humanist (with editorial bones)",
        "palette": {"primary": "#F1ECDE", "accent": "#C8BEA4", "bg": "#E6DCC4", "text": "#F1ECDE", "muted": "#1A1A18", "border": "#736D5A"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "tufte-dataink": {
        "name": "Edward Tufte / Maximum Data-Ink",
        "school": "Information Architecture",
        "palette": {"primary": "#FBFAF6", "accent": "#D8D2C2", "bg": "#1B1B1A", "text": "#FBFAF6", "muted": "#A6300E", "border": "#3E4A5C"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "vercel-mesh": {
        "name": "Vercel (Gradient Mesh Era)",
        "school": "Modern Tool / Builder SaaS (also touches Motion / Experimental)",
        "palette": {"primary": "#000000", "accent": "#000000", "bg": "#0A0A0A", "text": "#000000", "muted": "#111111", "border": "#1F1F1F"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
    "vignelli-swiss-helvetica": {
        "name": "Vignelli / Swiss International",
        "school": "Information Architecture",
        "palette": {"primary": "#000000", "accent": "#8A8A8A", "bg": "#FFFFFF", "text": "#000000", "muted": "#E2231A", "border": "#F5C518"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "0px",
        "shadow": "none",
        "signature": "",
        "anti_patterns": "",
    },
    "y2k-retrofuturism": {
        "name": "Y2K / Frutiger Aero Retrofuturism",
        "school": "Specialty / Genre",
        "palette": {"primary": "#A3D5FF", "accent": "#FFFFFF", "bg": "#E0E4EA", "text": "#A3D5FF", "muted": "#5FC9F8", "border": "#FF66C4"},
        "typography": {"heading": "Inter, sans-serif", "body": "Inter, sans-serif"},
        "radius": "2px",
        "shadow": "0 1px 8px rgba(0,0,0,0.08)",
        "signature": "",
        "anti_patterns": "",
    },
}

DEFAULT_STYLE = "linear"
